# Generated by Django 4.1.4 on 2022-12-12 16:51

from django.db import migrations, models
import django.db.models.deletion
import to_do.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=to_do.models.one_week_hence)),
                ('todo_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='to_do.todolist')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
